name: Refapp JiraServer Integration


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.')"
        
      - name: Replace ArtifactId Value
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --inplace  -N s=http://maven.apache.org/POM/4.0.0 -u "/s:project/s:artifactId" -v microsoft-teams-integration pom.xml

      - name: Replace Version Value
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --inplace  -N s=http://maven.apache.org/POM/4.0.0 -u "/s:project/s:version" -v ${{ steps.date.outputs.date }}${{ github.run_number }} pom.xml

      - name: Replace FinalName Value
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --inplace  -N s=http://maven.apache.org/POM/4.0.0 -u "/s:project/s:build/s:finalName" -v microsoft-teams-integration-${{ steps.date.outputs.date }}${{ github.run_number }} pom.xml

      - name: Replace ProjectName Value
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --inplace  -N s=http://maven.apache.org/POM/4.0.0 -u "/s:project/s:name" -v Microsoft-Teams-for-Jira-Server-(Integration) pom.xml

      - name: Run a powershell script
        run: ./setEnvironmentProperties.ps1 "src/main/resources/integration.properties" "a3955064-f94d-4848-93d5-7fefac2b4c6d" "microsoft-teams-integration" "https://jira-server-integration.msteams-atlassian.com/JiraGateway?atlasId=%s&atlasUrl=%s&pluginVersion=%s" ${{ steps.date.outputs.date }}${{ github.run_number }} "https://jira-server-integration.msteams-atlassian.com"
        shell: pwsh

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: RefAppAddon.Integration.${{ steps.date.outputs.date }}${{ github.run_number }}
          path: ${{ github.workspace }}/target/*.jar
